### ISSUE TITLE
updating cubist with last "official" release

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/Cubist#3]
I recently noted that CUBIST model has been updated recently. [https://www.rulequest.com/cr209.html](url) and the C code is publicaly available. Would it be possible to incorporate the changes in a forthcoming release of the package?

**Comment by topepo** [comment]
Not yet I don't think: 

> Licensees who purchased Cubist since 27 January 2015 are welcome to upgrade to Release 2.09.
> Click the appropriate link(s) below to download Release 2.09. You will be asked to re-enter your licence ID before running the system. If you use our public source code for reading and interpreting Cubist models, you should also download the latest version.

The tar file doesn't seem to include the model generation code but only the public prediction code. 

The [GPL version](https://www.rulequest.com/download.html) appears to be Release 2.07 GPL Edition.
