### ISSUE TITLE
error summing up cases

### ISSUE THREAD

**Issue by joezUoE** [topepo/Cubist#4]
Hi,

I found a difference in the sum of the amount of cases when applying the test data specified in the manual of cubist.

library(Cubist)
library(mlbench)
data(BostonHousing)
BostonHousing$chas <- as.numeric(BostonHousing$chas) - 1
set.seed(1)
inTrain <- sample(1:nrow(BostonHousing), floor(.8*nrow(BostonHousing)))
trainingPredictors <- BostonHousing[ inTrain, -14]
trainingOutcome <- BostonHousing$medv[ inTrain]
modelTree <- cubist(x = trainingPredictors, y = trainingOutcome)

Read 404 cases (14 attributes) from undefined.data

Model:

  Rule 1: [88 cases, mean 13.81, range 5 to 27.5, est err 2.10]

    if
        nox > 0.668
    then
        outcome = 2.07 + 3.14 dis - 0.35 lstat + 18.8 nox + 0.007 b
                  - 0.12 ptratio - 0.008 age - 0.02 crim

  Rule 2: [153 cases, mean 19.54, range 8.1 to 31, est err 2.16]

    if
        nox <= 0.668
        lstat > 9.59
    then
        outcome = 34.81 - 1 dis - 0.72 ptratio - 0.056 age - 0.19 lstat + 1.5 rm
                  - 0.11 indus + 0.004 b

  Rule 3: [39 cases, mean 24.10, range 11.9 to 50, est err 2.73]

    if
        rm <= 6.23
        lstat <= 9.59
    then
        outcome = 11.89 + 3.69 crim - 1.25 lstat + 3.9 rm - 0.0045 tax
                  - 0.16 ptratio

  Rule 4: [128 cases, mean 31.31, range 16.5 to 50, est err 2.95]

    if
        rm > 6.23
        lstat <= 9.59
    then
        outcome = -1.13 + 1.6 crim - 0.93 lstat + 8.6 rm - 0.0141 tax
                  - 0.83 ptratio - 0.47 dis - 0.019 age - 1.1 nox

The sum of the cases is 208 and I checked the 4 mentioned individuals are already in rule 1 but because rule 3 and 4 does not take nox >0.668 into account they are in both rule 1 and rule 3 and 4.

Best wishes,
J

**Comment by topepo** [comment]
Training set points can fall into multiple rules. The rules are first created from terminal nodes in trees and, at that point, do not overlap. As rules get pruned, they begin to have overlapping sets.
