### ISSUE TITLE
Weird behaviour when variable name begins with "sample"

### ISSUE THREAD

**Issue by PhilippPro** [topepo/Cubist#5]
When a variable name contains the word "sample" cubist only predicts 0s. Very weird behaviour. ;)

Example:
```
> library(Cubist)
> data = data.frame(measure.value = rnorm(10, 1000), sample.fraction = rnorm(10, 1000))
> mod = cubist(x = data[,2, drop = F], y = data[,1])
> predict(mod, newdata = data[,2, drop = F])
 [1] 0 0 0 0 0 0 0 0 0 0
> data = data.frame(measure.value = rnorm(10, 1000), abc = rnorm(10, 1000))
> mod = cubist(x = data[,2, drop = F], y = data[,1])
> predict(mod, newdata = data[,2, drop = F])
 [1] 1000.684 1000.684 1000.684 1000.684 1000.684 1000.684 1000.684 1000.684 1000.684 1000.684
```

**Comment by topepo** [comment]
That looks like an issue with the C sources. There isn't any mention of reserved words in [the documentation](https://www.rulequest.com/cubist-win.html#name) but that looks to be the issue. 

I could:

1. throw an error when there is a variable by that name, or
1. have the function rename it to something (e.g. `..sample..` or similar) before the model fit and prediction.

Neither is very appealing to me. Do you have a preference?

**Comment by PhilippPro** [comment]
The best thing would be, that the error does not occur. ;) Probably the second option would be the best, if the user does not notice anything (e.g. the variables in the model at the end do not have other names).

**Comment by PhilippPro** [comment]
There is still a problem when there is an extra variable after the "sample" variable. 

```
library(Cubist)
data = data.frame(measure.value = rnorm(10, 1000), sample.fraction = rnorm(10, 1000), mtry = runif(1000, 0, 1))
mod = cubist(x = data[,-1, drop = F], y = data[,1])
# Fehler in `[.data.frame`(x, , as.character(splits$variable[i])) : 
#  undefined columns selected
```
I think the problem is not completely solved. ;)
