### ISSUE TITLE
All the prediction results are 0 when row number of predicted data frame >8000

### ISSUE THREAD

**Issue by SongchaoChen** [topepo/Cubist#7]
Recently, I used Cubist (version 0.0.19) to predict large data. I found that all of my predictions are 0.
Then I make a test as follows:
`y <- predict(gm, m@data[1:8000,])` 
`y <- predict(gm, m@data[1:10000,])` 
The first row returned correct predictions while all the redictions in the second row were 0.
I attached two test files (gm and m) in the link below:
https://drive.google.com/file/d/0B1UXahMqUgk6SE5JUldscmlWT1U/view?usp=sharing
https://drive.google.com/file/d/0B1UXahMqUgk6dTBrbmdiMXNMb1U/view?usp=sharing
Could you help me to solve the problem? Thanks a lot.
Songchao

**Comment by topepo** [comment]
Can you provide a _small_ reproducible example and the result of `sessionInfo()`?

**Comment by SongchaoChen** [comment]
Here is the code for test.
`library(Cubist)
gm <- readRDS("mCUBIST_cv1.rds")
m <- readRDS("T100.rds")
y <- predict(gm, m@data[1:8000,])
y <- predict(gm, m@data[1:10000,])`

For the data, please download via precious two links.

`> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2`

Many thanks for your help.

**Comment by topepo** [comment]
Can you run `sessionInfo()` after loading `Cubist`? 

Also, a **smaller** example will help expedite the testing.

**Comment by SongchaoChen** [comment]
Sorry for my mistake. I used my another laptop, it reported the same problem.
A much samller data is avaiable via the links:
https://drive.google.com/file/d/0B1UXahMqUgk6dTBrbmdiMXNMb1U/view?usp=sharing
https://drive.google.com/file/d/0B1UXahMqUgk6Q240ZjJFQjZNZ0k/view?usp=sharing

Code for test is here:
`library(Cubist)`
`library(sp)`
`gm <- readRDS("mCUBIST_cv1.rds")`
`m <- readRDS("T100.rds")`
`y <- predict(gm, m[1:8000,])`
`y <- predict(gm, m[1:10000,])`

`sessionInfo()` is as follows:
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sp_1.2-5        Cubist_0.0.19   lattice_0.20-35

loaded via a namespace (and not attached):
[1] compiler_3.4.0 magrittr_1.5   plyr_1.8.4     tools_3.4.0    reshape2_1.4.2
[6] Rcpp_0.12.11   stringi_1.1.5  grid_3.4.0     stringr_1.2.0 

Many thanks for your time.
Best regards,
Songchao

**Comment by topepo** [comment]
I can't reproduce it on my side:
```r
> library(Cubist)
Loading required package: lattice
> library(sp)
> gm <- readRDS("mCUBIST_cv1.rds")
> m <- readRDS("T100.rds")
> y <- predict(gm, m[1:8000,])
> y <- predict(gm, m[1:10000,])
> 
> 
> str(y)
 num [1:10000] 0 0 0 0 0 0 0 0 0 0 ...
```

Do you have Rtools installed (so that you could try to compile from the sources)?

**Comment by topepo** [comment]
(Sorry for the false start there)

The issue is that some of the data that you are trying to predict have levels that were not in the data set:
```r
> cat(gm$names)
| Generated using R version 3.3.2 (2016-10-31)
| on mer. oct. 18 11:32:37 2017
| function call: makeNamesFile(x = x, y = y, label = control$label, comments = TRUE)
outcome.

outcome: continuous.
ASPECT: continuous.
BDFOREST: C1,C10,C2,C3,C4,C5,C6,C7,C8,C9.
CESBIO: C1,C11,C12,C13,C14,C15,C16,C17,C2,C3,C4,C5,C6,C8,C9.
CLC06: C1,C10,C11,C12,C13,C14,C15,C2,C3,C4,C5,C6,C7,C8,C9.
CTI: continuous.
CURVATURE: continuous.
ECOCLIM: C1,C10,C2,C3,C4,C5,C6,C7,C8,C9.
ELEVATION: continuous.
EROS: continuous.
EXPOSITION: continuous.
GRAVIMETRY: continuous.
IDPR: continuous.
NPPMAX: continuous.
NPPMEAN: continuous.
NPPMIN: continuous.
PM: C1,C10,C2,C3,C4,C5,C6,C7,C8,C9.
RAINFALL: continuous.
ROUGHNESS: continuous.
SCALEPOS: continuous.
SLOPE: continuous.
SLOPEASCOS: continuous.
SOIL: C1,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C2,C3,C4,C5,C6,C7,C8,C9.
TEMPMAX: continuous.
TEMPMEAN: continuous.
TEMPMIN: continuous.
TYPO: C1,C2,C3,C4,C5,C6,C7,C8.

> unique(m$CESBIO)
 [1] "C15" "C2"  "C1"  "C8"  "C4"  "C3"  "C6"  "C5"  "C9"  "C13" "C7"  "C12" "C17"
```
This leads to the internal messages that
```
*** line 3269 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 6347 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7767 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7879 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7880 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7996 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7998 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
```

Although the predictions for these cases have values:
```r
> y <- predict(gm, m[1:8000,])[bad_vals]
> y
[1] 101.76560  92.30835  61.09860  60.51820  61.54100  60.88600  60.03040
```
(I'll figure that out)

Why did it fail with 10000 and not 8000? It reaches its limit on error messages:
```r
*** line 3269 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 6347 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7767 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7879 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7880 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7996 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 7998 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 8113 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 8115 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'
*** line 8230 of `undefined.cases':
    bad value of `C7' for attribute `CESBIO'

Error limit exceeded
```

I'll improve this a bit so that we can tell what is going on. You'll have to refit the model with a training set that has all the levels of all the factors or excluded those. Another option is to use the `recipes` package, which has a way to automatically encode new values as "other". See `step_other` in that package.

**Comment by SongchaoChen** [comment]
Many thanks for your detailed reply. I will do as you suggested.
Have a nice weekend.
Songchao

**Comment by topepo** [comment]
I've having the function fail on the first error now. That's the better solution.
